#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
#. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
#set -x

wmake $targetType compressible
wmake $targetType twoPhaseMixture
wmake $targetType twoPhaseProperties
wmake $targetType incompressible
wmake $targetType myinterfacePropertiesSSF
wmake $targetType myimmiscibleSemiCompressibleTwoPhaseMixtureSSF

#------------------------------------------------------------------------------
