#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
#. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
#set -x

wclean $targetType incompressible
wclean $targetType compressible
wclean $targetType twoPhaseMixture
wclean $targetType myinterfacePropertiesSSF
wclean $targetType twoPhaseProperties
wclean $targetType myimmiscibleSemiCompressibleTwoPhaseMixtureSSF

#------------------------------------------------------------------------------
